25 firebase frontend
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #12
Opened 2023-03-14 14:39 UTC by bochka123

2023-03-14 20:13 UTC, tatianahutii requested changes

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +                JSON.parse(localStorage.getItem('user')!);
Please get rid of duplication codes and you need to unsubscribe after every subscribe

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +                JSON.parse(localStorage.getItem('user')!);
you can use removeItem instead of setItem with null

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +                this.SetUserData(result.user);
```suggestion
                this.setUserData(result.user);
```

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +                this.httpService.post<any>(this.url, result.user);
Please do not use any

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +        return user !== null;
```suggestion
        return !!user;
```

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +        const user = JSON.parse(localStorage.getItem('user')!);
Could you please move this to a separate method? As I see you use JSON.parse(localStorage.getItem('user')!) a few times

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +        return this.AuthLogin(new auth.FacebookAuthProvider()).then((res: any) => {
see previous comments

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +        return this.AuthLogin(new auth.GoogleAuthProvider()).then((res: any) => {
see previous comments

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +    AuthLogin(provider: any) {
see previous comments

2023-03-14 20:13 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +        };
Do we really need all of these fields in local storage?

2023-03-15 11:41 UTC, KaterynaHerasymiva submitted a review, later dismissed

2023-03-15 17:11 UTC, tatianahutii requested changes

2023-03-15 17:11 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +                window.alert(error.message);
Please fix all warnings

2023-03-15 17:11 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +                this.httpService.post<firebase.User | null>(this.url, result.user);
Do we have this method in the backend?

2023-03-15 17:11 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +                localStorage.setItem('user', JSON.stringify(this.userData));
we need to store a token as well and refresh it when it expires

2023-03-15 17:11 UTC, tatianahutii commented on frontend/src/app/shared/models/enums/Sex.ts
> +    NonBinary = 'Non-binary',
Will this work with the backend?

2023-03-15 17:11 UTC, tatianahutii commented on frontend/src/app/shared/models/IUser.ts
> +    isBanned?: boolean;
Instead of doing properties optional it would be better to use Partial in a place where you don't need all required fields

2023-03-15 17:11 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +        );
why do we need this?

2023-03-15 23:34 UTC, KaterynaHerasymiva submitted a review, later dismissed

2023-03-16 20:30 UTC, tatianahutii approved these changes

2023-03-16 22:21 UTC, Anatolii-Ivanov approved these changes

2023-03-16 22:22 UTC, merged