107 add notifications
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #125
Opened 2023-04-02 11:34 UTC by ishootdice

- Modified DTOs for notifications, notification types(NotificationType), added mapping profiles for them
- Added necessary endpoints for NotificationController
- Added add and get methods for notifications depending on their types
- Modified template for user notifications
- Added some logic for user notifications component
- Added notification of lesson enroll
<img width="1440" alt="Screenshot 2023-04-02 at 13 25 16" src="https://user-images.githubusercontent.com/99364412/229350222-e29439b4-dc5f-4513-be00-e2edf8ec2bba.png">

2023-04-02 12:42 UTC, Anatolii-Ivanov commented
Can you order notifications by date?

2023-04-02 12:57 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +            _messageProducer.Init("notifier", "");
Please, move to appsettings

2023-04-02 12:57 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +            } ?? throw new InvalidOperationException("The notification type doesn't correspond to any of available types." +
you can throw in switch/case directly

2023-04-02 12:57 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +                ImageId = sender.ImageId
Still question with imageId

2023-04-02 12:57 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +                    u => u.UserId,
Github actions

2023-04-02 12:57 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/user-notification/user-notification.component.ts
> +        });
Let's use map

2023-04-02 19:20 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +                ImageId = sender.ImageId
Created ticket for it

2023-04-02 19:22 UTC, Anatolii-Ivanov approved these changes

2023-04-02 19:58 UTC, tatianahutii requested changes

2023-04-02 19:58 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/NotificationsProfile.cs
> +        CreateMap<string, NotificationType>().ConvertUsing<StringToEnumConverter<NotificationType>>();
why do we need this mapper?

2023-04-02 19:58 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
> +            lessonsFromContext = lessonsFromContext.Where(x => x.Tags.Any(y => tagsName != null && tagsName.Contains(y.Name)));
do we need this check? we have it in an if expression

2023-04-02 19:58 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +            notifications.AddRange(await GetNotificationsAsync(NotificationType.friendshipAcception));
should be 1 request instead of 4

2023-04-02 19:58 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +                _ => new List<NotificationDto>()
I believe we can combine all of these requests

2023-04-02 19:58 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +        }
we can combine there two requests

2023-04-02 19:58 UTC, tatianahutii commented on frontend/src/app/shared/components/user-notification/user-notification.component.ts
> +            .subscribe();
use httpService in the component is not a good practice

2023-04-02 19:58 UTC, tatianahutii commented on frontend/src/app/shared/components/user-notification/user-notification.component.ts
> +    getNotificationTypeIcon(type: string) {
use enum here

2023-04-02 19:58 UTC, tatianahutii commented on frontend/src/app/shared/components/user-notification/user-notification.component.ts
> +    }
could you please move this to a helper and create consts for all magic numbers

2023-04-02 19:58 UTC, tatianahutii commented on frontend/src/app/shared/components/user-notification/user-notification.component.ts
> +        }));
why do we do this in frontend and backend? it would be better to do this only in one place

2023-04-05 13:04 UTC, Anatolii-Ivanov approved these changes

2023-04-05 13:15 UTC, merged