163: fixed
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #126
Opened 2023-04-02 12:59 UTC by KaterynaHerasymiva

2023-04-02 13:09 UTC, Anatolii-Ivanov requested changes

2023-04-02 13:09 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
> +                IsDisabled = t.Subscribers.Select(u => u.Id).Any(id => id == _authService.UserId)
You can make Any(u => u.Id == _authService.UserId)

2023-04-02 13:09 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
> +                IsDisabled = t.Subscribers.Select(u => u.Id).Any(id => id == _authService.UserId)
And changed isDisabled to isSubscribed or something like this

2023-04-02 16:36 UTC, KaterynaHerasymiva commented
> Consider changing the button text if the user is registered for the lesson

good point, I think there should be a task for it. Because for now when user enrolls the lesson button text is changed to `Expired`. I find it inconsistent..

2023-04-03 07:46 UTC, Anatolii-Ivanov approved these changes

2023-04-03 15:01 UTC, Anatolii-Ivanov approved these changes

2023-04-03 18:50 UTC, merged