156 real user profile photo
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #128
Opened 2023-04-02 15:13 UTC by ihor-mk

If user has profile photo, it is shown on card on Social tab.
If user hasn’t profile photo, his initials with colored background has to be shown (look in header)

2023-04-02 16:05 UTC, ihor-mk commented
![Screenshot_1](https://user-images.githubusercontent.com/96182715/229364748-8f1ff517-606e-423c-82a6-80e622a76367.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/96182715/229364750-20e24c66-e1ea-418b-a818-db28d9efd051.jpg)

2023-04-02 17:46 UTC, Anatolii-Ivanov approved these changes

2023-04-02 18:20 UTC, SidletskyiOlexandr approved these changes

2023-04-02 19:17 UTC, tatianahutii requested changes

2023-04-02 19:17 UTC, tatianahutii commented on frontend/src/app/shared/components/avatar/avatar.component.ts
> +        const userName = this.fullName.split(' ');
it would be better to pass first and last name separatly

2023-04-03 10:48 UTC, SidletskyiOlexandr approved these changes

2023-04-03 10:49 UTC, Anatolii-Ivanov approved these changes

2023-04-05 13:17 UTC, tatianahutii approved these changes

2023-04-05 13:17 UTC, merged