12 Implemented filter section component
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #13
Opened 2023-03-14 14:46 UTC by ishootdice

2023-03-14 14:48 UTC, Anatolii-Ivanov commented
Can you add a screenshot?

2023-03-14 14:53 UTC, ishootdice commented
Yeah, of course
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/99364412/225040175-6e4389d3-b8fd-4c82-9d4b-2369b420878c.png">

2023-03-14 15:39 UTC, tatianahutii requested changes

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.html
> +                <div *ngIf="this.selectedLanguageFilters.size > 0" class="filters-count-group">
```suggestion
                <div *ngIf="this.selectedLanguageFilters.size" class="filters-count-group">
```

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.html
> +                    <span *ngIf="this.selectedLanguageFilters.size > 0">
```suggestion
                    <span *ngIf="this.selectedLanguageFilters.size">
```

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.html
> +                    <span *ngIf="this.selectedLanguageFilters.size === 0">
```suggestion
                    <span *ngIf="!this.selectedLanguageFilters.size">
```

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.html
> +                        {{this.selectedLanguageFilters.keys().next().value}}
We need to simplify this line

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.html
> +                <div *ngIf="this.selectedTopicsFilters.size > 0" class="filters-count-group">
see previous comments

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.html
> +                            <input type="checkbox" [checked]="this.selectedTopicsFilters.has(topic.title)" (click)="selectTopic(topic.title)">
Move this to the ts file and replace it in all similar places

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.html
> +        </div>
Do we really need so many divs?

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.html
> +            <div style="margin: 0px;" *ngFor="let selectedTopic of this.selectedTopicsFilters">
Please do not use inline styles

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.sass
> +    width: 195px
In would be better do not use px

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.sass
> +
please remove all extra lines

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.sass
> +    height: 228px
Please avoid using so specific px sizes

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.spec.ts
> +import { FilterSectionComponent } from './filter-section.component';
You can delete this file for now

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.ts
> +  public selectedTopicsFilters = new Set();
We need to create a general dropdown component and reuse it in all places where we need it

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.ts
> +    {
Please move this to .utils.ts file

2023-03-14 15:39 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.ts
> +    }
Please avoid mutations

2023-03-14 20:17 UTC, tatianahutii requested changes

2023-03-14 20:17 UTC, tatianahutii commented on frontend/src/app/components/filter-section/filter-section.component.ts
> +  removeLangLevel(title: any){
Please do not use any

2023-03-14 20:17 UTC, tatianahutii commented on frontend/src/app/components/dropdown/dropdown.component.ts
> +  }
Delete empty methods

2023-03-14 20:17 UTC, tatianahutii commented on frontend/src/app/components/dropdown/dropdown.component.ts
> +    })
you need to unsibscribe

2023-03-14 20:17 UTC, tatianahutii commented on frontend/src/app/components/dropdown/dropdown.component.sass
> +
Please delete extra space

2023-03-14 20:17 UTC, tatianahutii commented on frontend/src/app/components/dropdown/dropdown.component.sass
> +        background-color: #fff
Please use color variables

2023-03-14 20:55 UTC, tatianahutii submitted a review, later dismissed

2023-03-15 08:21 UTC, Anatolii-Ivanov approved these changes

2023-03-17 08:44 UTC, SidletskyiOlexandr approved these changes

2023-03-17 10:20 UTC, merged