159 161 remove none filters+multiselect native language
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #142
Opened 2023-04-04 07:57 UTC by KaterynaHerasymiva

2023-04-04 08:08 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/dropdown/dropdown.component.ts
> +        return this.btnLabel;//
Remove comment

2023-04-04 08:08 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-04-04 09:37 UTC, SidletskyiOlexandr submitted a review, later dismissed

2023-04-04 14:36 UTC, KaterynaHerasymiva commented on frontend/src/app/shared/components/dropdown/dropdown.component.ts
> +        return this.btnLabel;//
fixed

2023-04-04 16:39 UTC, SidletskyiOlexandr submitted a review, later dismissed

2023-04-04 17:00 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-04-04 17:31 UTC, tatianahutii requested changes

2023-04-04 17:31 UTC, tatianahutii commented on frontend/src/app/shared/components/dropdown/dropdown.component.html
> +        <div *ngIf="selectedItems.length === 0" class="dropdown-btn-title" >
```suggestion
        <div *ngIf="!selectedItems.length" class="dropdown-btn-title" >
```

2023-04-04 17:31 UTC, tatianahutii commented on frontend/src/app/shared/components/dropdown/dropdown.component.html
> +        <div *ngIf="selectedItems.length > 0" class="dropdown-btn-title-when-selected" >
```suggestion
        <div *ngIf="selectedItems.length" class="dropdown-btn-title-when-selected" >
```

2023-04-04 17:31 UTC, tatianahutii commented on frontend/src/app/shared/components/dropdown/dropdown.component.html
> +        <div *ngIf="selectedItems.length > 0" class="dropdown-btn-subtitle">
```suggestion
        <div *ngIf="selectedItems.length" class="dropdown-btn-subtitle">
```

2023-04-05 08:28 UTC, Anatolii-Ivanov approved these changes

2023-04-05 13:16 UTC, tatianahutii approved these changes

2023-04-05 13:16 UTC, merged