116 Generate Zoom links
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #147
Opened 2023-04-04 14:24 UTC by ayomanetsan

This PR adds a feature to create Zoom meeting links for the lesson. Upon the creation of a lesson, **two** links will be generated: one for the **host** and one for the **students**.

2023-04-04 17:29 UTC, tatianahutii requested changes

2023-04-04 17:29 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +            "https://api.zoom.us/v2/users/me/meetings",
it would be better to move this to the appsettings

2023-04-04 17:29 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +            "https://api.zoom.us/v2/users/me/meetings",
at least base url

2023-04-04 17:29 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +        dynamic meeting = JsonConvert.DeserializeObject(responseBody);
github actions warnings

2023-04-04 17:30 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +        dynamic meeting = JsonConvert.DeserializeObject(responseBody);
and code smells

2023-04-05 08:36 UTC, Anatolii-Ivanov requested changes

2023-04-05 08:36 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +    }
Can you move it to some sort of helper function?

2023-04-05 08:36 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +        using var httpClient = new HttpClient();
Use IHttpClientFactory instead (as DI)

2023-04-05 08:36 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +        );
I'd move token generation and adding it to client to a separate function

2023-04-05 08:36 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +            )
The same, to helper/private/static function (select one)

2023-04-05 08:36 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +        dynamic meeting = JsonConvert.DeserializeObject(responseBody);
Create a model with needed fields (it won't deserialize all other)

2023-04-05 08:36 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
> +    }
Can be done in one line

2023-04-05 13:46 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Domain/EasySpeak.Domain.csproj
Why you created this project?
Domain means main project with logic... In our case it's Core

2023-04-05 19:27 UTC, merged