Create static lessons page
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #15
Opened 2023-03-14 16:53 UTC by ayomanetsan

2023-03-14 17:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.sass
> +    margin: 0
Please no global styles in general files

2023-03-14 17:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.sass
> +    padding: 31px 57px
round such values to 30/55

2023-03-14 17:50 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.sass
> +    padding: 31px 57px
Everywhere

2023-03-14 17:50 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.sass
> +    height: 20.62px
No decimals in css please

2023-03-14 17:53 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/youtube-player/youtube-player.component.sass
> +    background-color: #000
Use variables for colors please

2023-03-14 17:53 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/youtube-player/youtube-player.component.ts
> +    videoId = 'xqAriI87lFU';
Make it as Input

2023-03-14 17:54 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/youtube-player/youtube-player.component.ts
> +        this.apiLoaded = true;
Formatting
Are you sure this is needed?

2023-03-14 17:54 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/shared.module.ts
> +    declarations: [LoadingSpinnerComponent, NotFoundComponent, YoutubePlayerComponent],
New import - new line

2023-03-14 17:57 UTC, Anatolii-Ivanov requested changes

2023-03-14 17:57 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +        <div class="card">
ngFor please

2023-03-14 17:57 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +                <img src="../../../../assets/lesson-mocks/Photo-4.png"
Make it loaded from ts

2023-03-14 17:57 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +                    </svg>
Svgs to separate files please

2023-03-14 17:57 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +                    </svg>
Everywhere

2023-03-14 17:57 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +                <h3 class="lesson-theme">The Real New Yorker’s Sandwich</h3>
Data from ts

2023-03-14 17:57 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +                    <div class="topic">biology</div>
Data from ts file

2023-03-14 18:43 UTC, tatianahutii commented
@ayomanetsan Could you please add screenshots?

2023-03-15 08:25 UTC, Anatolii-Ivanov requested changes

2023-03-15 08:25 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +                        stroke-linecap="round" stroke-linejoin="round" />
svg

2023-03-15 08:39 UTC, Anatolii-Ivanov approved these changes

2023-03-15 08:40 UTC, SidletskyiOlexandr approved these changes

2023-03-15 08:40 UTC, merged