Add validation for past time whene creating lesson
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #157
Opened 2023-04-06 20:27 UTC by ihor-mk

2023-04-06 22:29 UTC, Anatolii-Ivanov requested changes

2023-04-06 22:29 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-create/lessons-create.component.html
> +                    <p *ngIf="isPast">That time has passed</p>
Lesson with past date can't be created

2023-04-06 22:29 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-create/lessons-create.component.html
> +                    <p *ngIf="isPast">That time has passed</p>
Selected time has passed, Select future one

2023-04-06 22:29 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-create/lessons-create.component.ts
> +        const timeNow = moment(Date.now()).toDate();
moment() is the same as moment(Date.now())

2023-04-06 22:29 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-create/lessons-create.component.ts
> +        this.isPast = startAt < timeNow;
Can you compare it via moment?

2023-04-09 20:01 UTC, tatianahutii approved these changes

2023-04-10 07:23 UTC, Anatolii-Ivanov approved these changes

2023-04-10 07:30 UTC, merged