205, 213 & 215 Bugfixes
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #164
Opened 2023-04-09 09:15 UTC by ayomanetsan

2023-04-09 09:17 UTC, Anatolii-Ivanov requested changes

2023-04-09 09:17 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.ts
> +        const birthDateMoment = moment(userDetails.birthDate, 'YYYY-MM-DD').add(1, 'day');
Can you maybe find the reason? As it maybe more global problem

2023-04-09 09:17 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.ts
> +        userDetails.birthDate = birthDateMoment.format('YYYY-MM-DD');
And why we pass date as string?...

2023-04-09 09:48 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.ts
> +        const birthDateMoment = moment(userDetails.birthDate, 'YYYY-MM-DD').add(1, 'day');
But how it happens, that on register page it works and on user details - doesn't?

2023-04-10 07:49 UTC, Anatolii-Ivanov approved these changes

2023-04-10 07:51 UTC, bochka123 approved these changes

2023-04-10 07:52 UTC, merged