230 add tad id in request
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #194
Opened 2023-04-11 19:56 UTC by potapchuk-anna

2023-04-11 20:29 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-04-11 20:31 UTC, tatianahutii requested changes

2023-04-11 20:31 UTC, tatianahutii commented on frontend/src/app/modules/social-page/filter-section/filter-section.component.ts
> +                name: tag.name,
```suggestion
                ...tag,
```

2023-04-12 00:52 UTC, tatianahutii approved these changes

2023-04-12 07:00 UTC, Anatolii-Ivanov approved these changes

2023-04-12 08:46 UTC, merged