114 change my password
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #195
Opened 2023-04-11 20:49 UTC by NLMOTS

2023-04-11 21:03 UTC, Anatolii-Ivanov requested changes

2023-04-11 21:03 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user-profile/user-password-change/user-password-change.component.ts
> +                break;
Implement it as validation (like on login page), not as toastr

2023-04-11 21:03 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user-profile/user-password-change/user-password-change.component.ts
> +                this.router.navigate(['timetable']);
No need to redirect

2023-04-11 21:03 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user-profile/user-password-change/user-password-change.component.ts
> +    }
Can you implement it via form?

2023-04-13 17:05 UTC, Anatolii-Ivanov approved these changes

2023-04-14 00:36 UTC, bochka123 approved these changes

2023-04-14 00:36 UTC, merged