Multiple bugfixes
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #217
Opened 2023-04-12 16:53 UTC by ayomanetsan

2023-04-12 17:45 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-04-12 18:11 UTC, tatianahutii requested changes, later dismissed

2023-04-12 18:11 UTC, tatianahutii commented on frontend/src/app/shared/data/languageLevel.ts
> +    C2 = 'C2 (Proficient)',
it would be better to have mapper for this
Enam should contains only raw data (the same as in the backend)

2023-04-13 09:03 UTC, Anatolii-Ivanov approved these changes

2023-04-13 09:12 UTC, NadiaMaksymchuk approved these changes

2023-04-13 09:12 UTC, merged