183 update seeding
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #223
Opened 2023-04-12 23:41 UTC by potapchuk-anna

2023-04-12 23:48 UTC, tatianahutii requested changes

2023-04-12 23:48 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.DAL/Migrations/20230412231240_SeedingUpdated.Designer.cs
Please update Readme with this changes

2023-04-13 00:02 UTC, tatianahutii approved these changes

2023-04-13 07:40 UTC, Anatolii-Ivanov approved these changes

2023-04-13 10:36 UTC, merged