Bugfix lesson card questions
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #228
Opened 2023-04-13 14:08 UTC by ShevchenkoKirilo

Fixed bugs 166, 216, 272

2023-04-13 14:23 UTC, KaterynaHerasymiva approved these changes, later dismissed

2023-04-13 17:43 UTC, tatianahutii requested changes

2023-04-13 17:43 UTC, tatianahutii commented on frontend/src/app/modules/lessons/lesson/lesson.component.ts
> +            this.isQuestionsOpened = true;
ternary operator

2023-04-13 17:43 UTC, tatianahutii commented on frontend/src/app/modules/lessons/lesson/lesson.component.ts
> +            observer.observe(document.body, { childList: true, subtree: true });
separate method

2023-04-13 17:43 UTC, tatianahutii commented on frontend/src/app/modules/lessons/lesson/lesson.component.ts
> +                new Date() > new Date(this.lesson.startAt) ||
duplication

2023-04-13 17:43 UTC, tatianahutii commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +                    (questionsOpened)="onLessonOpenedQuestions(i + lessonsColumn1.length)"></app-lesson>
looks a little bit strange 
try to refactor these lines

2023-04-13 20:32 UTC, KaterynaHerasymiva submitted a review, later dismissed

2023-04-14 11:51 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user/teachers-page/teachers-page.component.html
> +                <div class="lesson" *ngFor="let lesson of day.lessonsColumn2; let j = index">
I guess you don't need indexes anymore

2023-04-14 11:52 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
> +            <div class="lesson" *ngFor="let lesson of lessonsColumn2; let i = index">
The same here

2023-04-14 11:59 UTC, merged