42 Implemented UserProfile component
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #40
Opened 2023-03-21 08:00 UTC by ishootdice

- Created UserProfile component
- Created child components that UserProfile needs
- Registered routes for all components
- UserProfile and UserDetails components was made according to design
- Created data utils entities fro this components
- Added assets
- Created UserService with getById and update methods
- Created API endpoints for sending and retrieving simple user's

2023-03-21 08:25 UTC, Anatolii-Ivanov requested changes
Please, also check Seeder file, as it seems that it has some exception with 'Sex' field
![image](https://user-images.githubusercontent.com/57347711/226551881-fbce37da-9d76-4287-8346-c12907450873.png)

2023-03-21 08:25 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.DAL/Entities/User.cs
> +    }
You can use enums from db entities, no need to duplicate them)

2023-03-21 08:25 UTC, Anatolii-Ivanov commented on frontend/src/app/core/services/user.service.ts
> +    public updateUser(userId: number, userUpdates: IUserInfo) {
userUpdates -> updatedUser

2023-03-21 08:25 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user-profile/user-profile-routing.module.ts
> +                path: 'details/:id',
No id (at least for now), user can see only his profile

2023-03-21 11:10 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/UserDto.cs
> +}
Still github actions
![image](https://user-images.githubusercontent.com/57347711/226589194-6351ac19-1f61-4b41-bb68-bc550eb55139.png)

2023-03-21 11:14 UTC, Anatolii-Ivanov requested changes

2023-03-21 11:14 UTC, ishootdice commented
<img width="703" alt="image" src="https://user-images.githubusercontent.com/99364412/226589862-574b03f5-6a27-4d03-8d8c-6919c09e0a0d.png">

2023-03-21 12:47 UTC, Anatolii-Ivanov approved these changes

2023-03-21 14:06 UTC, Anatolii-Ivanov approved these changes

2023-03-21 14:21 UTC, tatianahutii requested changes

2023-03-21 14:21 UTC, tatianahutii commented on frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.ts
> +        this.userService.getUser(0)
it would be better to create a const for hard-coded userId and use it

2023-03-21 14:21 UTC, tatianahutii commented on frontend/src/app/modules/user-profile/user-profile.module.ts
> +        MatInputModule,
You need to use Material module instead of this

2023-03-21 14:21 UTC, tatianahutii commented on frontend/src/app/shared/data/sex.ts
> +    notspecified = "Don't want to specify"
check if this will work with the backend

2023-03-21 20:55 UTC, tatianahutii requested changes

2023-03-21 20:55 UTC, tatianahutii commented on frontend/src/app/app.module.ts
> +        MatIconModule,
It would be better to import Material module

2023-03-22 17:01 UTC, Anatolii-Ivanov approved these changes

2023-03-23 15:16 UTC, tatianahutii approved these changes

2023-03-23 18:25 UTC, tatianahutii approved these changes

2023-03-23 18:42 UTC, merged