47 user card
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #41
Opened 2023-03-21 12:42 UTC by KaterynaHerasymiva

2023-03-21 14:06 UTC, Anatolii-Ivanov approved these changes

2023-03-21 14:33 UTC, tatianahutii requested changes

2023-03-21 14:33 UTC, tatianahutii commented on frontend/src/app/modules/user-card/user-card.component.html
> +            <div class="up_2">
Class name should be more informative and try to avoid so many levels of div

2023-03-21 14:33 UTC, tatianahutii commented on frontend/src/app/modules/user-card/user-card.component.html
> +                            <img class="flag" src="../../../assets/user-card-icons/canada-test-flag.svg">
canada-test-flag is not a good name

2023-03-21 14:33 UTC, tatianahutii commented on frontend/src/app/modules/user-card/user-card.component.sass
> +.spinner-container
it would be better to create a separate shared component for this type of spinner and call it (round-progress-bar)

2023-03-21 19:35 UTC, KaterynaHerasymiva commented on frontend/src/app/modules/user-card/user-card.component.html
> +                        <img src="../../../assets/user-card-icons/facebook.svg" alt="facebook-icon">
@tatianahutii I've found that aliases can be used for *.ts or *. sass files. Should I place it to *.ts?

2023-03-22 07:54 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/user-card/user-card.component.html
> +<!--                </div>-->
Do you still need this lines?

2023-03-22 07:55 UTC, Anatolii-Ivanov requested changes

2023-03-22 07:55 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/shared.module.ts
> +    declarations: [LoadingSpinnerComponent, NotFoundComponent, YoutubePlayerComponent, DropdownComponent, ModalComponent, ConfirmComponent, RoundProgressBarComponent],
Please, make every element on new line, like exports

2023-03-22 11:24 UTC, KaterynaHerasymiva commented on frontend/src/app/modules/user-card/user-card.component.html
> +<!--                </div>-->
sure  not

2023-03-22 11:25 UTC, KaterynaHerasymiva commented on frontend/src/app/shared/shared.module.ts
> +    declarations: [LoadingSpinnerComponent, NotFoundComponent, YoutubePlayerComponent, DropdownComponent, ModalComponent, ConfirmComponent, RoundProgressBarComponent],
fixed

2023-03-22 11:36 UTC, Anatolii-Ivanov approved these changes

2023-03-22 17:12 UTC, merged