35 video call
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #42
Opened 2023-03-21 21:45 UTC by potapchuk-anna

2023-03-22 08:31 UTC, Anatolii-Ivanov requested changes

2023-03-22 08:31 UTC, Anatolii-Ivanov commented on frontend/src/app/core/services/webrtc-utils.service.ts
> +}
Just imagine that you open this code for the first time and trying understand what's happening here

2023-03-22 08:31 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Hubs/SignalRtcHub.cs
> +        }
And these two functions

2023-03-22 23:01 UTC, Anatolii-Ivanov approved these changes
Thank you) Looks much better
I hope that it works ;)

2023-03-23 08:04 UTC, bochka123 approved these changes

2023-03-23 08:07 UTC, merged