36 get notifications
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #44
Opened 2023-03-22 12:30 UTC by ihor-mk

2023-03-22 18:05 UTC, Anatolii-Ivanov requested changes

2023-03-22 18:05 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/user-notification/user-notification.component.ts
> +            }
It's better to implement in the way, that you will pass parameters on connection start and then send from backend only to those users, who needs this

2023-03-23 13:52 UTC, ihor-mk commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Hubs/NotificationHub.cs
> +    }
I use it to create a hub only, and then get context

2023-03-23 15:00 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-03-23 18:32 UTC, tatianahutii requested changes

2023-03-23 18:32 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
> +            var user = await _context.Users.Where(u => u.Id == _firebaseAuthService.UserId).FirstOrDefaultAsync();
```suggestion
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == _firebaseAuthService.UserId);
```

2023-03-23 18:32 UTC, tatianahutii commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/EasySpeak.Notifier.WebAPI.csproj
> +    <ProjectReference Include="..\..\EasySpeak.Core\EasySpeak.Core.Common\EasySpeak.Core.Common.csproj" />
Please add this to Dockerfile

2023-03-23 18:32 UTC, tatianahutii commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Program.cs
> +        .WithOrigins("http://localhost:4200")
```suggestion
        .WithOrigins("http://*:4200")
```

2023-03-23 18:32 UTC, tatianahutii commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Services/ConsumerHostedService.cs
> +                        _hubContext.Clients.All.SendAsync($"Notification_{data.Email.ToLower()}", JsonConvert.SerializeObject(data));
please fix github actions warnings

2023-03-23 18:32 UTC, tatianahutii commented on frontend/src/app/core/hubs/notifications-hub.service.ts
> +    // eslint-disable-next-line no-empty-function
please do not use eslint-disable-next-line

2023-03-23 18:32 UTC, tatianahutii commented on frontend/src/app/shared/components/user-notification/user-notification.component.html
> +<div *ngIf="notifications.length > 0">
```suggestion
<div *ngIf="notifications.length">
```

2023-03-23 18:32 UTC, tatianahutii commented on frontend/src/app/shared/components/user-notification/user-notification.component.ts
> +            this.notifications.push(broadcastMessage);
please get rid of mutations

2023-03-24 01:40 UTC, tatianahutii commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/EasySpeak.Notifier.WebAPI.csproj
> +    <ProjectReference Include="..\..\EasySpeak.Core\EasySpeak.Core.Common\EasySpeak.Core.Common.csproj" />
still need this

2023-03-24 07:34 UTC, ihor-mk commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/EasySpeak.Notifier.WebAPI.csproj
> +    <ProjectReference Include="..\..\EasySpeak.Core\EasySpeak.Core.Common\EasySpeak.Core.Common.csproj" />
This reference is present in Dockerfile

2023-03-24 07:57 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-03-24 08:07 UTC, NLMOTS approved these changes
If using http necessarily, keep this like that

2023-03-24 08:14 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-03-24 08:19 UTC, NLMOTS submitted a review, later dismissed

2023-03-24 09:06 UTC, Anatolii-Ivanov approved these changes

2023-03-24 09:27 UTC, NLMOTS approved these changes
http error solved, good work

2023-03-24 10:28 UTC, merged