26 email sending service
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #46
Opened 2023-03-22 20:22 UTC by bochka123

2023-03-22 21:09 UTC, Anatolii-Ivanov requested changes

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on .gitignore
> +**/EasySpeak.Emailer.WebAPI/appsettings.json
Please, right click on project name, "User Secrets", add hidden items there, don't exclude appsettings please
Or use appsettings.Development.json

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on README.md
> +| EasySpeak.**Emailer**  | 7109 |
Let's go with port 5000 something? Like 5090

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/EmailerController.cs
> +        }
Can you move this logic to a separate service, so we can reuse it from code? As we won't send mails by HTTP requests

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Emailer/EasySpeak.Emailer.WebAPI/Program.cs
> +});
Can you move this function to a separate file async (IValidator<NewMailDto> validator, IMailService mailService, NewMailDto mailDto) =>...
And then use it here

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Emailer/EasySpeak.Emailer.WebAPI/Properties/launchSettings.json
> +      "applicationUrl": "https://localhost:7109;http://localhost:5109",
You can change project port here

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/EmailerController.cs
> +            _httpClient.BaseAddress = new Uri("https://localhost:7109/api/emailer/send");
Move to appsettings

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Emailer/EasySpeak.Emailer.WebAPI/Services/SendGridMailService.cs
> +            var from = new EmailAddress("easymeats.service@gmail.com", "EasySpeak");
Email -> appsettigns

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/appsettings.json
Leave it, please

2023-03-22 21:09 UTC, Anatolii-Ivanov commented on docker-compose.apps.prod.yml
> +        image: bochka123/easyspeak_emailer:latest
Change to tatihutii/easyspeak_emailer, it may be changed and tania's account is more persistent here)

2023-03-23 09:11 UTC, Anatolii-Ivanov requested changes

2023-03-23 09:11 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/appsettings.json
Get it back

2023-03-23 09:12 UTC, bochka123 commented on backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/appsettings.json
But it is there

2023-03-23 09:49 UTC, Anatolii-Ivanov approved these changes

2023-03-23 09:51 UTC, potapchuk-anna approved these changes

2023-03-23 09:51 UTC, merged