57 Defined enums and implemented mapping for them
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #48
Opened 2023-03-23 15:24 UTC by ishootdice

- Enums filled with the same values that we have on FE
- Created Mapping Profiles for enums such as contry, timezone and language
- Removed validation for enums inside NewUserDtoValidator
- Removed hardcoded list of countries in Sign-In component on FF
- Some namespaces had typos which I corrected, also made AddFirebaseApp private

2023-03-24 15:51 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/auth/sign-up/sign-up.component.ts
> +    Countries;
Set empty array "= []"

2023-03-24 15:57 UTC, tatianahutii requested changes

2023-03-24 15:57 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Helpers/EnumMappingHelper.cs
> +        var attribute = field.GetCustomAttributes(typeof(DescriptionAttribute), false)
Fix warnings

2023-03-24 15:58 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Helpers/EnumMappingHelper.cs
> +        var attribute = field.GetCustomAttributes(typeof(DescriptionAttribute), false)
And please fix Code smels

2023-03-26 11:49 UTC, Anatolii-Ivanov approved these changes

2023-03-26 17:14 UTC, tatianahutii approved these changes

2023-03-26 17:14 UTC, merged