81 Fixed spinner when loading questions
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #63
Opened 2023-03-24 12:53 UTC by ShevchenkoKirilo

Now spinner always appears in the card while loading, spinner disappears if we get an error

2023-03-26 09:59 UTC, Anatolii-Ivanov commented
We need spinner on opening one question, not for the whole page, please

2023-03-26 17:39 UTC, ShevchenkoKirilo commented
![image](https://user-images.githubusercontent.com/71650121/227793889-c1307f17-3e71-4979-a1e0-dd7cae29723f.png)

2023-03-27 20:12 UTC, tatianahutii requested changes

2023-03-28 14:49 UTC, ShevchenkoKirilo commented on frontend/src/app/modules/lessons/lesson/lesson.component.sass
> +    left: 49%
fixed

2023-03-28 15:40 UTC, tatianahutii submitted a review, later dismissed

2023-03-28 16:39 UTC, Anatolii-Ivanov approved these changes

2023-03-28 16:59 UTC, ShevchenkoKirilo commented on frontend/src/app/modules/lessons/lesson/lesson.component.sass
> +    left: 49%
It makes big white space above spinner. Already tried this. Justify content and align items don't help

2023-03-28 18:21 UTC, tatianahutii approved these changes

2023-03-28 18:24 UTC, Anatolii-Ivanov approved these changes

2023-03-28 18:29 UTC, merged