71 Created directive to show and hide password
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #80
Opened 2023-03-27 17:14 UTC by ShevchenkoKirilo

![image](https://user-images.githubusercontent.com/71650121/228016338-c730645c-0f82-461e-b04a-e754d57bed03.png)
This directive can be applied to any password field

2023-03-27 17:16 UTC, ShevchenkoKirilo commented
![image](https://user-images.githubusercontent.com/71650121/228016728-28fb40d7-6cfb-4bd8-b0ce-87928700ef95.png)
![image](https://user-images.githubusercontent.com/71650121/228016775-2f5d4238-e55e-441f-90a0-35a3db74237b.png)

2023-03-27 17:28 UTC, Anatolii-Ivanov commented
Make right padding the same as left

2023-03-27 17:40 UTC, ShevchenkoKirilo commented
> Make right padding the same as left

![image](https://user-images.githubusercontent.com/71650121/228022380-de70b5b7-3a5e-4006-a474-d1819459f633.png)

2023-03-27 19:08 UTC, Anatolii-Ivanov approved these changes

2023-03-27 20:24 UTC, tatianahutii requested changes

2023-03-27 20:24 UTC, tatianahutii commented on frontend/src/app/shared/directives/password-visibility.directive.ts
> +export class PasswordVisibilityDirective {
You can implement this functionality without directive

2023-03-27 20:24 UTC, tatianahutii commented on frontend/src/app/shared/directives/password-visibility.directive.ts
> +export class PasswordVisibilityDirective {
https://nitishkaushik.com/show-hide-password-in-angular-with-angular-material/

2023-03-28 18:22 UTC, tatianahutii approved these changes

2023-03-28 18:24 UTC, merged