add crud service and controller for user profile
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #81
Opened 2023-03-27 18:52 UTC by SidletskyiOlexandr

2023-03-27 19:09 UTC, Anatolii-Ivanov commented
![image](https://user-images.githubusercontent.com/57347711/228042371-b10c9f01-4aa1-4015-9faf-c76ae8defbd4.png)

2023-03-27 19:19 UTC, Anatolii-Ivanov requested changes

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IAzureBlobStorageService.cs
> +        Task<UploadFileDto> UpdateFileAsync(long fileId, NewFileDto newFileDto);
UploadFile -> File/FileData/EasySpeakFile 
The same with UploadFile

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/AzureBlobStorageService.cs
> +                CreatedAt = DateTime.UtcNow,
We have CreatedAt date set automatically

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/AzureBlobStorageService.cs
> +                UpdatedAt = DateTime.UtcNow,
We don't plan to update files, remove, create new

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/AzureBlobStorageService.cs
> +            return _mapper.Map<UploadFileDto>(file);
Remove/create new

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/AzureBlobStorageService.cs
> +    }
Move to separate service (file)

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/AzureBlobStorageService.cs
> +            var provider = new FileExtensionContentTypeProvider();
Either var or types everywhere

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/AzureBlobStorageService.cs
> +        }
+extension

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/UploadFile/NewFileDto.cs
> +        public string FolderPath { get; set; } = null!;
Won't be here, it's up to you set up folders

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/UploadFile/NewFileDto.cs
> +        public string FolderPath { get; set; } = null!;
Generally we should have the same folder(blob container) for all profile pictures

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.DAL/Context/EasySpeakCoreContext.cs
> +
One new line

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.DAL/Entities/UploadFile.cs
> +    public class UploadFile : Entity<long>
Not UploadFile, refer higher

2023-03-27 19:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.WebAPI/appsettings.json
> +    "ConnectionString": "DefaultEndpointsProtocol=https;AccountName=easyspeak;AccountKey=7oWpdsuvuP952P0pIkSzqMD1xAq371tJJ9WHzhb+2vFC4sb/ckx9Fa1d5BcVGZ3WBlGMkAp61Kdu+AStPHATNg==;EndpointSuffix=core.w
Really bad idea

2023-03-28 14:53 UTC, SidletskyiOlexandr commented on backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/UserProfileController.cs
> +        public async Task<IActionResult> AddFile(IFormFile file)
In my task i should only add endpoint to update user profile photo without logic adding photo to user profile

2023-03-28 14:57 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/AzureBlobStorageService.cs
> +        }
Not fixed

2023-03-28 15:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.WebAPI/appsettings.json
> +  "EmailSendURI": "https://localhost:5090/api/emailer/send"
Why you removed connection string name...

2023-03-28 15:19 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/UserProfileController.cs
> +            var res = await _easySpeakFileService.AddFileAsync(fileDto);
Can you move this call to like UserService, where at the end this file will be assigned to user as a profile picture
Maybe you will need to create migration

Then call userService.UpdateProfilePhoto from this controller

2023-03-29 12:35 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
> +            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == userId);
Please, use userId from firebaseAuthService

2023-03-29 12:35 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
> +            return photoDto;
Returning just url will be fine

2023-03-29 13:15 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-03-29 13:22 UTC, potapchuk-anna submitted a review, later dismissed

2023-03-29 13:57 UTC, Anatolii-Ivanov approved these changes

2023-03-29 14:30 UTC, potapchuk-anna approved these changes

2023-03-29 14:31 UTC, merged