88 Completed auth flow
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #85
Opened 2023-03-28 14:52 UTC by ishootdice

- SignIn and SignUp components rework
- Moved styles from SignIn and SignUp to AuthPageComponent styles 
- Created endpoint for user update on backend side, modified UserService
- Made forms inside SignIn and SignUp templates more responsive
- Changed routing after SignIn and SignUp
- Created couple entities on Backend for user update

2023-03-28 16:14 UTC, ishootdice commented
<img width="1440" alt="Screenshot 2023-03-28 at 17 18 41" src="https://user-images.githubusercontent.com/99364412/228303348-45e36433-8607-4d09-8daa-be3ceffec4eb.png">

2023-03-28 16:14 UTC, ishootdice commented
<img width="1440" alt="Screenshot 2023-03-28 at 17 19 40" src="https://user-images.githubusercontent.com/99364412/228303447-da2bd62e-db3a-46ed-8c2c-f4f18463dcfb.png">

2023-03-28 16:25 UTC, NadiaMaksymchuk approved these changes

2023-03-28 16:34 UTC, tatianahutii requested changes
Looks good. Only a few small fixes

2023-03-28 16:34 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
> +            user.Tags = _context.Tags.Where(t => tagsNames.Contains(t.Name)).ToList();
await

2023-03-28 16:34 UTC, tatianahutii commented on frontend/src/app/modules/auth/sign-in/sign-in.component.ts
> +                Validators.pattern('^(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\\d@$!%*?&\\.]{6,}$'),
please create a separate shared file for regex storing

2023-03-28 16:34 UTC, tatianahutii commented on frontend/src/app/modules/auth/sign-up/sign-up.component.ts
> +        this.ages = Ages;
move to a separate method

2023-03-28 16:34 UTC, tatianahutii commented on frontend/src/app/modules/auth/sign-up/sign-up.component.ts
> +                this.router.navigate(['topics']);
show a notification after an user creating

2023-03-28 16:34 UTC, tatianahutii commented on frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.ts
> +            });
to a separate method

2023-03-28 16:41 UTC, Anatolii-Ivanov commented
From screenshot
Only selected field should have this blue border/shadow
Can you make right part the same way it's done on landing page, please

2023-03-28 16:43 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
> +            var tagsNames = userDto.Tags.Select(x => x.Name).ToList();
Maybe we can just assign tags to existing user without changing other fields?

2023-03-28 16:44 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/auth/sign-in/sign-in.component.html
> +                </div>
Can you make it via code and then just show correct exception here?

2023-03-28 16:45 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/auth/sign-in/sign-in.component.html
> +
The same

2023-03-28 16:46 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/auth/sign-up/sign-up.component.html
> +            </div>
The same for all errors here (You can create two functions, one to check if it should be shown, second - what should be shown

2023-03-28 16:46 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/auth/sign-up/sign-up.component.ts
> +        this.ages = Ages;
and ngOnInit

2023-03-29 00:30 UTC, ishootdice commented
<img width="1439" alt="Screenshot 2023-03-29 at 03 29 25" src="https://user-images.githubusercontent.com/99364412/228396186-675e3390-4054-4bc9-a4b2-98e64b620c26.png">

2023-03-29 08:29 UTC, NadiaMaksymchuk approved these changes

2023-03-29 13:00 UTC, Anatolii-Ivanov commented on backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/UserController.cs
> +        [HttpPost]
Please, don't create endpoint with same url even if they have different parameters
You can name this one /users/tags

2023-03-30 09:58 UTC, Anatolii-Ivanov submitted a review, later dismissed

2023-03-30 13:59 UTC, tatianahutii requested changes

2023-03-30 13:59 UTC, tatianahutii commented on backend/EasySpeak.Core/EasySpeak.Core.DAL/Entities/User.cs
> +        public ICollection<Tag> Tags { get; set; } = new List<Tag>();
please fix warnings in this file

2023-03-30 13:59 UTC, tatianahutii commented on frontend/src/app/modules/auth/sign-up/sign-up.component.ts
> +                this.router.navigate(['topics']);
this won't work as you expected

2023-03-30 13:59 UTC, tatianahutii commented on frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.ts
> +            });
still, need this

2023-03-30 14:07 UTC, NadiaMaksymchuk submitted a review, later dismissed

2023-03-30 16:21 UTC, tatianahutii requested changes

2023-03-30 16:21 UTC, tatianahutii commented on frontend/src/app/modules/auth/sign-up/sign-up.component.ts
> +            );
```suggestion
     this.authService.signUp(this.email.value, this.password.value)
         .then(() => {
             this.createUser()
                  .pipe( this.untilThis,)
                  .subscribe(
                      () => {
                          this.toastr.success('Account successfully registered', 'Succes!');
                           this.router.navigate(['topics']);
                       },
                       (error) => {
                           this.toastr.error(error.message, 'Sign up');
                       })
                   })

```

2023-03-30 16:33 UTC, Anatolii-Ivanov approved these changes

2023-03-30 16:35 UTC, merged