Added chat page
BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak pull request #95
Opened 2023-03-29 22:29 UTC by bochka123

![image](https://user-images.githubusercontent.com/98846587/228681726-27901708-c4c6-435e-89f9-2c42d73cd390.png)
I have issue with date of messages, but I will fix it in the morning with the fresh head
For now, pleasy, just look at the code and tell me please if there is something more to fix, thanks)
Good night)

2023-03-29 22:38 UTC, Anatolii-Ivanov requested changes

2023-03-29 22:38 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                "
Use https://angular.io/api/common/NgClass

2023-03-29 22:38 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                <span>3</span>
Can you make it dynamic?

2023-03-29 22:38 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                "
Better to use it everywhere

2023-03-29 22:38 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                )
Move to ts and check via moment()

2023-03-29 22:38 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                        {{getMonthName(message.createdAt.getMonth()).slice(0, 3)}}
Use DatePipe https://angular.io/api/common/DatePipe

2023-03-29 22:38 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                )
Better to check all dates with it

2023-03-29 22:38 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                                {{message.createdAt.getHours() < 10 ? '0'+message.createdAt.getHours() : message.createdAt.getHours()}}
DatePipe

2023-03-29 22:41 UTC, Anatolii-Ivanov commented
Concerning screen - please, check font styles on the right side, as they look different from design
And make one line messages centered in block vertically, please

2023-03-30 11:40 UTC, bochka123 commented
![image](https://user-images.githubusercontent.com/98846587/228824711-94f8a6f7-a768-4273-a68e-b6ec54daf5ef.png)
![image](https://user-images.githubusercontent.com/98846587/228824848-1428cc7b-31bb-4ec8-bec9-6dd89727a778.png)

2023-03-30 11:44 UTC, Anatolii-Ivanov requested changes

2023-03-30 11:44 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                                }}
Can you make it in ts?
And maybe move messages to a separate component

2023-03-30 11:44 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                            {{ setLastDate(message.createdAt) }}
Please map data, so you won't set anything in html

2023-03-30 18:35 UTC, Anatolii-Ivanov requested changes

2023-03-30 18:35 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/message-group/message-group.component.ts
> +        return date.toLocaleDateString('en-US', { day: 'numeric', month: 'short' });
Use moment please

2023-03-30 18:35 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/chat-page/chat-page.component.ts
> +        });
Use reduce()
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce
And moment for comparing dates

2023-03-30 19:16 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/chat/message-group/message-group.component.ts
> +        if (moment(date).isSame(moment(today).startOf('day'))) {
moment(today) is the same as moment()

moment().addDays('days', -1) is the same as moment(yesterday)

2023-03-30 19:24 UTC, Anatolii-Ivanov approved these changes

2023-03-30 19:31 UTC, tatianahutii requested changes

2023-03-30 19:31 UTC, tatianahutii commented on frontend/src/app/modules/chat/chat-page/chat-page.component.html
> +                  'read': person.numberOfUnreadMessages === 0
```suggestion
                  'unread': person.numberOfUnreadMessages,
                  'read': !person.numberOfUnreadMessages
```

2023-03-30 19:31 UTC, tatianahutii commented on frontend/src/app/modules/chat/chat-page/chat-page.component.ts
> +            this.messages.push({
```suggestion
            this.messages. = [ ...messages, {
```

2023-03-30 21:12 UTC, Anatolii-Ivanov approved these changes

2023-03-31 00:58 UTC, tatianahutii submitted a review, later dismissed

2023-03-31 07:08 UTC, Anatolii-Ivanov approved these changes

2023-03-31 07:37 UTC, ShevchenkoKirilo approved these changes

2023-03-31 07:41 UTC, merged